<?php
use App\Application\Acopios\{ConsultarAcopios, GestionarAcopios};
use App\Infrastructure\Rutas\RutaAcopio;
use App\Models\User;
use Illuminate\Support\Facades\Gate;
use Illuminate\Validation\ValidationException;
use Livewire\Component;
use Livewire\WithPagination;
use Mary\Traits\Toast;

new class extends Component {
    use WithPagination, Toast;
    public string $search = ''; public string $estado = ''; public string $rutaId = ''; public string $recolectorId = '';
    public string $fechaDesde = ''; public string $fechaHasta = ''; public bool $modal = false; public ?int $detalleId = null;
    public array $form = ['ruta_id' => '', 'fecha_operativa' => '', 'turno' => 'primera_vuelta', 'observaciones' => ''];
    public string $motivo = ''; public ?int $correccionId = null; public string $litros = ''; public string $observacion = ''; public string $correccionMotivo = '';
    public function boot(): void { Gate::authorize('administrar-acopios'); }
    public function updatedSearch(): void { $this->resetPage(); } public function updatedEstado(): void { $this->resetPage(); } public function updatedRutaId(): void { $this->resetPage(); } public function updatedRecolectorId(): void { $this->resetPage(); }
    public function create(): void { Gate::authorize('administrar-acopios'); $this->reset('form'); $this->form['fecha_operativa'] = now()->toDateString(); $this->resetValidation(); $this->modal = true; }
    public function show(int $id): void { Gate::authorize('administrar-acopios'); $this->detalleId = $id; $this->resetValidation(); }
    public function closeDetail(): void { $this->detalleId = null; $this->resetValidation(); }
    public function save(): void { try { app(GestionarAcopios::class)->createJourney(auth()->id(), $this->form); $this->modal = false; $this->success('Jornada abierta correctamente.'); } catch (ValidationException $e) { $this->fillErrors($e); } }
    public function finish(string $state): void { try { app(GestionarAcopios::class)->changeState(auth()->id(), $this->detalleId, $state, $this->motivo); $this->motivo = ''; $this->success($state === 'cerrada' ? 'Jornada cerrada.' : 'Jornada anulada.'); } catch (ValidationException $e) { $this->fillErrors($e); } }
    public function editDelivery(int $id, string $litros, string $observacion = ''): void { $this->correccionId = $id; $this->litros = $litros; $this->observacion = $observacion; $this->resetValidation(); }
    public function correct(): void { try { app(GestionarAcopios::class)->correctDelivery(auth()->id(), $this->correccionId, ['litros' => $this->litros, 'observacion' => $this->observacion, 'motivo' => $this->correccionMotivo]); $this->correccionId = null; $this->success('Entrega corregida y auditada.'); } catch (ValidationException $e) { $this->fillErrors($e); } }
    private function fillErrors(ValidationException $e): void { $this->resetValidation(); foreach ($e->errors() as $field => $messages) { $this->addError($field, $messages[0]); } $this->error(collect($e->errors())->flatten()->first()); }
    public function with(): array { $filters = ['search' => $this->search, 'estado' => $this->estado, 'ruta_id' => $this->rutaId ?: null, 'recolector_id' => $this->recolectorId ?: null, 'fecha_desde' => $this->fechaDesde ?: null, 'fecha_hasta' => $this->fechaHasta ?: null]; return ['jornadas' => app(ConsultarAcopios::class)->adminList(auth()->id(), $filters), 'detalle' => $this->detalleId ? app(ConsultarAcopios::class)->adminFind(auth()->id(), $this->detalleId) : null, 'rutas' => RutaAcopio::query()->orderBy('codigo')->get(['id', 'codigo', 'nombre'])->map(fn ($r) => ['id' => $r->id, 'name' => $r->codigo.' — '.$r->nombre])->all(), 'recolectores' => User::query()->whereHas('roles', fn ($q) => $q->where('name', 'recolector')->where('guard_name', 'web'))->orderBy('name')->get(['id', 'name'])->all(), 'headers' => [['key' => 'fecha_operativa', 'label' => 'Fecha'], ['key' => 'turno', 'label' => 'Turno'], ['key' => 'ruta', 'label' => 'Ruta'], ['key' => 'recolector', 'label' => 'Recolector'], ['key' => 'productores_atendidos', 'label' => 'Productores'], ['key' => 'litros', 'label' => 'Litros'], ['key' => 'estado', 'label' => 'Estado']]]; }
}; ?>

<div class="space-y-6">
    <x-header title="Acopios" subtitle="Jornadas y entregas registradas en campo" separator progress-indicator><x-slot:actions><x-button label="Nueva jornada" icon="o-plus" wire:click="create" class="btn-primary" /></x-slot:actions></x-header>
    <x-card shadow><div class="grid grid-cols-1 md:grid-cols-3 xl:grid-cols-6 gap-4"><x-input label="Buscar" wire:model.live.debounce.300ms="search" placeholder="Código o ruta" /><x-input label="Desde" type="date" wire:model.live="fechaDesde" /><x-input label="Hasta" type="date" wire:model.live="fechaHasta" /><x-select label="Ruta" :options="$rutas" option-value="id" wire:model.live="rutaId" placeholder="Todas" placeholder-value="" /><x-select label="Recolector" :options="$recolectores" option-value="id" wire:model.live="recolectorId" placeholder="Todos" placeholder-value="" /><x-select label="Estado" :options="[['id'=>'abierta','name'=>'Abierta'],['id'=>'cerrada','name'=>'Cerrada'],['id'=>'anulada','name'=>'Anulada']]" wire:model.live="estado" placeholder="Todos" placeholder-value="" /></div><div class="overflow-x-auto mt-5"><x-table :headers="$headers" :rows="$jornadas" with-pagination>@scope('cell_estado', $j)<span class="badge {{ $j['estado']==='abierta'?'badge-success':($j['estado']==='anulada'?'badge-error':'badge-neutral') }}">{{ ucfirst($j['estado']) }}</span>@endscope @scope('cell_turno', $j){{ $j['turno']==='primera_vuelta'?'Primera vuelta':'Segunda vuelta' }}@endscope @scope('actions', $j)<x-button label="Consultar" wire:click="show({{ $j['id'] }})" class="btn-ghost btn-sm" />@endscope <x-slot:empty><div class="p-8 text-center">No se encontraron jornadas.</div></x-slot:empty></x-table></div></x-card>
    @if($detalle)<x-card :title="$detalle['ruta'].' · '.$detalle['fecha_operativa']" shadow><div class="space-y-4"><div class="flex justify-between"><span class="badge">{{ ucfirst($detalle['estado']) }}</span><x-button label="Cerrar detalle" wire:click="closeDetail" class="btn-ghost btn-sm" /></div><p>Recolector: {{ $detalle['recolector'] }} · {{ $detalle['turno']==='primera_vuelta'?'Primera vuelta':'Segunda vuelta' }}</p>@if($detalle['estado']==='abierta')<div class="flex gap-2"><x-button label="Cerrar jornada" wire:click="finish('cerrada')" wire:confirm="¿Cerrar esta jornada? Las entregas quedarán solo de consulta." class="btn-primary" /><x-button label="Anular jornada" wire:click="finish('anulada')" class="btn-error" /></div>@endif @if($detalle['estado']==='abierta')<x-input label="Motivo de anulación (si corresponde)" wire:model="motivo" />@endif<div class="overflow-x-auto"><table class="table"><thead><tr><th>Productor</th><th>Litros</th><th>Hora</th><th>Observación</th><th></th></tr></thead><tbody>@forelse($detalle['entregas'] as $e)<tr wire:key="entrega-{{ $e['id'] }}"><td>{{ $e['productor'] }}</td><td>{{ $e['litros'] }}</td><td>{{ $e['recolectada_at'] }}</td><td>{{ $e['observacion'] }}</td><td>@if($detalle['estado']==='abierta')<x-button label="Corregir" wire:click="editDelivery({{ $e['id'] }}, '{{ $e['litros'] }}', @js($e['observacion'] ?? ''))" class="btn-ghost btn-sm" />@endif</td></tr>@empty<tr><td colspan="5">No hay entregas registradas.</td></tr>@endforelse</tbody></table></div>@if($correccionId)<x-form wire:submit="correct"><x-input label="Litros nuevos" wire:model="litros" type="number" step="0.001" /><x-textarea label="Observación" wire:model="observacion" /><x-textarea label="Motivo obligatorio" wire:model="correccionMotivo" /><x-slot:actions><x-button label="Guardar corrección" type="submit" class="btn-primary" /></x-slot:actions></x-form>@endif</div></x-card>@endif
    <x-modal wire:model="modal" title="Nueva jornada"><x-form wire:submit="save"><x-select label="Ruta" :options="$rutas" option-value="id" wire:model="form.ruta_id" placeholder="Selecciona una ruta" /><x-input label="Fecha operativa" type="date" wire:model="form.fecha_operativa" /><x-select label="Turno" :options="[['id'=>'primera_vuelta','name'=>'Primera vuelta'],['id'=>'segunda_vuelta','name'=>'Segunda vuelta']]" wire:model="form.turno" /><x-textarea label="Observaciones" wire:model="form.observaciones" /><x-slot:actions><x-button label="Guardar" type="submit" class="btn-primary" spinner="save" /></x-slot:actions></x-form></x-modal>
</div>
