<?php
use App\Application\Ventas\ConsultarVentas;
use App\Application\Ventas\GestionarVentas;
use App\Application\Inventario\GestionarInventario;
use App\Application\Operacion\ReglasOperativas;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use Livewire\Component;
use Livewire\WithPagination;
use Livewire\Attributes\Locked;
use Mary\Traits\Toast;
new class extends Component {
    use WithPagination, Toast;
    public array $filters=['estado'=>'','cliente_id'=>''];
    public array $form=[];
    public array $customer=['nombre'=>'','categoria'=>'publico_general','productor_id'=>'','activo'=>true,'motivo'=>''];
    public array $pricing=[];
    public array $adjustment=[];
    public string $ruleReason='';
    public string $motivo='';
    public string $metodo='';
    public string $pagadaAt='';
    public bool $modal=false;
    #[Locked] public ?string $detailUuid=null;
    #[Locked] public ?int $customerId=null;
    public function boot(): void { Gate::authorize('administrar-ventas'); }
    public function mount(): void { $this->pricing=app(ReglasOperativas::class)->current('ventas')['valores']; $this->adjustment=['uuid'=>(string)Str::uuid(),'tipo'=>'paria_fresco','delta'=>'','motivo'=>'']; }
    public function updatedFilters(): void { Gate::authorize('administrar-ventas'); $this->resetPage(); }
    public function create(): void { Gate::authorize('administrar-ventas'); $this->resetValidation(); $this->form=['uuid'=>(string)Str::uuid(),'cliente_id'=>'','vendida_at'=>now()->format('Y-m-d\TH:i'),'descuento'=>'0.00','descontar_liquidacion'=>false,'observaciones'=>'','detalles'=>[['tipo'=>'paria_fresco','moldes'=>'1']]]; $this->modal=true; }
    public function addDetail(): void { Gate::authorize('administrar-ventas'); if(count($this->form['detalles']??[])<2) { $this->form['detalles'][]=['tipo'=>'paria_pasteurizado','moldes'=>'1']; } }
    public function removeDetail(int $index): void { Gate::authorize('administrar-ventas'); unset($this->form['detalles'][$index]); $this->form['detalles']=array_values($this->form['detalles']); }
    public function show(string $uuid): void { Gate::authorize('administrar-ventas'); app(ConsultarVentas::class)->find(auth()->id(),$uuid); $this->detailUuid=$uuid; $this->motivo=''; $this->metodo=''; $this->pagadaAt=now()->format('Y-m-d\TH:i'); $this->resetValidation(); }
    public function save(): void { Gate::authorize('administrar-ventas'); $this->perform(function (): void { $sale=app(GestionarVentas::class)->create(auth()->id(),$this->form); $this->show($sale->uuid); $this->modal=false; $this->success('Venta guardada como borrador.'); }); }
    public function runAction(string $action): void { Gate::authorize('administrar-ventas'); $this->perform(function () use($action): void { $service=app(GestionarVentas::class); match($action) { 'confirmar'=>$service->confirm(auth()->id(),$this->detailUuid),'pagar'=>$service->pay(auth()->id(),$this->detailUuid,['metodo_pago'=>$this->metodo,'pagada_at'=>$this->pagadaAt]),'anular'=>$service->annul(auth()->id(),$this->detailUuid,$this->motivo),default=>abort(404) }; $this->success('Operación registrada.'); }); }
    public function editCustomer(?int $id=null): void { Gate::authorize('administrar-ventas'); $this->customerId=$id; $this->customer=$id?app(ConsultarVentas::class)->customer(auth()->id(),$id):['nombre'=>'','categoria'=>'publico_general','productor_id'=>'','activo'=>true]; $this->customer['motivo']=''; $this->resetValidation(); }
    public function saveCustomer(): void { Gate::authorize('administrar-ventas'); $this->perform(function (): void { app(GestionarVentas::class)->customer(auth()->id(),$this->customer,$this->customerId); $this->editCustomer(); $this->success('Cliente guardado.'); }); }
    public function savePricing(): void { Gate::authorize('administrar-ventas'); $this->perform(function (): void { app(GestionarVentas::class)->pricing(auth()->id(),$this->pricing,$this->ruleReason); $this->success('Nueva versión de tarifas guardada.'); }); }
    public function adjustStock(): void { Gate::authorize('administrar-ventas'); $this->perform(function (): void { app(GestionarInventario::class)->adjust(auth()->id(),$this->adjustment); $this->adjustment['uuid']=(string)Str::uuid(); $this->adjustment['delta']=''; $this->success('Ajuste de inventario registrado.'); }); }
    private function perform(Closure $operation): void { $this->resetValidation(); try { $operation(); } catch(ValidationException $e) { foreach($e->errors() as $key=>$messages) { $this->addError($key,$messages[0]); } } catch(\Illuminate\Auth\Access\AuthorizationException $e) { throw $e; } catch(Throwable $e) { report($e); $this->addError('operacion','No se pudo completar la operación. Puedes reintentar.'); } }
    public function with(): array { $q=app(ConsultarVentas::class); return $q->options(auth()->id())+['records'=>$q->listing(auth()->id(),$this->filters),'movements'=>$q->movements(auth()->id()),'detail'=>$this->detailUuid?$q->find(auth()->id(),$this->detailUuid):null,'audit'=>$this->detailUuid?$q->audit(auth()->id(),$this->detailUuid):[],'rule'=>app(ReglasOperativas::class)->current('ventas'),'types'=>[['id'=>'paria_fresco','name'=>'Paria fresco'],['id'=>'paria_pasteurizado','name'=>'Paria pasteurizado']],'categories'=>[['id'=>'mayorista','name'=>'Mayorista'],['id'=>'proveedor','name'=>'Proveedor de leche'],['id'=>'publico_general','name'=>'Público general']]]; }
}; ?>
<div class="space-y-6">
    <x-header title="Inventario y ventas" subtitle="Existencias de queso Paria y ventas en soles" separator><x-slot:actions><x-button label="Nueva venta" wire:click="create" icon="o-plus" class="btn-primary" /></x-slot:actions></x-header>
    @if($errors->any())<div class="alert alert-error" role="alert"><ul>@foreach($errors->all() as $message)<li>{{ $message }}</li>@endforeach</ul></div>@endif
    <div class="grid md:grid-cols-2 gap-4">@foreach($stock as $item)<x-card :title="ucfirst(str_replace('_',' ',$item['tipo']))" wire:key="stock-{{ $item['tipo'] }}" shadow><p class="text-3xl font-bold">{{ $item['moldes'] }} moldes</p></x-card>@endforeach</div>
    <x-card title="Ventas" shadow>
        <div class="grid md:grid-cols-2 gap-3"><x-select label="Estado" wire:model.live="filters.estado" :options="[['id'=>'borrador','name'=>'Borrador'],['id'=>'confirmada','name'=>'Confirmada'],['id'=>'pagada','name'=>'Pagada'],['id'=>'anulada','name'=>'Anulada']]" placeholder="Todos" /><x-select label="Cliente" wire:model.live="filters.cliente_id" :options="$clientes" option-label="nombre" placeholder="Todos" /></div>
        <div class="overflow-x-auto"><table class="table"><thead><tr><th>Fecha</th><th>Cliente</th><th>Detalle</th><th>Total S/</th><th>Estado</th><th></th></tr></thead><tbody>@forelse($records as $sale)<tr wire:key="venta-{{ $sale->uuid }}"><td>{{ $sale->vendida_at->format('d/m/Y H:i') }}</td><td>{{ $sale->cliente_snapshot['nombre'] }}</td><td>@foreach($sale->detalles as $line)<p wire:key="line-{{ $line->id }}">{{ $line->moldes }} {{ str_replace('_',' ',$line->tipo) }}</p>@endforeach</td><td>{{ $sale->total }}</td><td>{{ $sale->estado }}</td><td><x-button label="Consultar" wire:click="show('{{ $sale->uuid }}')" class="btn-sm" /></td></tr>@empty<tr><td colspan="6">No hay ventas para estos filtros. Registra un cliente y crea una venta.</td></tr>@endforelse</tbody></table></div>{{ $records->links() }}
    </x-card>
    @if($detail)<x-card :title="'Venta '.$detail->uuid" shadow>
        <p>{{ $detail->cliente_snapshot['nombre'] }} · {{ $detail->estado }} · Tarifa versión {{ $detail->tarifa_aplicada['version'] }}</p>
        <ul>@foreach($detail->detalles as $line)<li wire:key="detalle-{{ $line->id }}">{{ str_replace('_',' ',$line->tipo) }}: {{ $line->moldes }} × S/ {{ $line->precio }} = S/ {{ $line->subtotal }}</li>@endforeach</ul>
        <p>Subtotal S/ {{ $detail->subtotal }} · Descuento S/ {{ $detail->descuento }} · Total S/ {{ $detail->total }}</p><p>{{ $detail->observaciones }}</p>
        @if($detail->descontar_liquidacion)<p class="text-warning">Compra marcada para descuento en liquidación semanal. Un pago directo cancela el saldo pendiente de descuento.</p>@endif
        @if($detail->estado==='borrador')<x-button label="Confirmar y descontar stock" wire:click="runAction('confirmar')" spinner="runAction" class="btn-primary mt-3" />@endif
        @if($detail->estado==='confirmada')<div class="grid md:grid-cols-2 gap-3 mt-3"><x-input label="Método de pago" wire:model="metodo" /><x-input label="Fecha de pago" type="datetime-local" wire:model="pagadaAt" /></div><x-button label="Registrar pago" wire:click="runAction('pagar')" spinner="runAction" class="mt-3" />@endif
        @if($detail->estado!=='anulada')<x-textarea label="Motivo obligatorio de anulación" wire:model="motivo" /><x-button label="Anular venta" wire:click="runAction('anular')" wire:confirm="¿Anular la venta y revertir su salida de inventario?" spinner="runAction" class="btn-error mt-3" />@endif
        <h3 class="font-semibold mt-4">Historial</h3>@foreach($audit as $item)<details wire:key="audit-{{ $item['id'] }}"><summary>{{ $item['accion'] }} · {{ $item['usuario']['name'] }} · {{ $item['created_at'] }} · {{ $item['motivo'] }}</summary><pre class="overflow-x-auto text-xs">{{ json_encode(['anterior'=>$item['anteriores'],'nuevo'=>$item['nuevos']],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre></details>@endforeach
    </x-card>@endif
    <x-card title="Clientes" shadow>
        <div class="overflow-x-auto"><table class="table"><thead><tr><th>Nombre</th><th>Categoría</th><th>Estado</th><th></th></tr></thead><tbody>@forelse($clientes as $client)<tr wire:key="cliente-{{ $client['id'] }}"><td>{{ $client['nombre'] }}</td><td>{{ str_replace('_',' ',$client['categoria']) }}</td><td>{{ $client['activo']?'Activo':'Inactivo' }}</td><td><x-button label="Editar" wire:click="editCustomer({{ $client['id'] }})" class="btn-sm" /></td></tr>@empty<tr><td colspan="4">Aún no hay clientes. Registra el primero.</td></tr>@endforelse</tbody></table></div>
        <x-form wire:submit="saveCustomer"><x-input label="Nombre" wire:model="customer.nombre" /><x-select label="Categoría" wire:model.live="customer.categoria" :options="$categories" />@if(($customer['categoria']??'')==='proveedor')<x-select label="Productor activo" wire:model="customer.productor_id" :options="$productores" placeholder="Seleccionar" />@if(empty($productores))<p>No hay productores activos disponibles.</p>@endif @endif<x-checkbox label="Activo" wire:model="customer.activo" />@if($customerId)<x-textarea label="Motivo de corrección" wire:model="customer.motivo" />@endif<x-slot:actions><x-button label="Nuevo cliente" wire:click="editCustomer" /><x-button label="Guardar cliente" type="submit" spinner="saveCustomer" class="btn-primary" /></x-slot:actions></x-form>
    </x-card>
    <x-card title="Tarifas y límite de proveedores" shadow><p>Versión {{ $rule['version'] }}. Los precios se copian en cada venta. Define el límite antes de vender a proveedores.</p><x-form wire:submit="savePricing"><div class="grid md:grid-cols-3 gap-3">@foreach($categories as $category)<x-input :label="$category['name'].' (S/ por molde)'" type="number" step="0.01" wire:model="pricing.precios.{{ $category['id'] }}" wire:key="tarifa-{{ $category['id'] }}" />@endforeach</div><x-input label="Límite de moldes para proveedores (sin definir bloquea nuevas ventas)" type="number" step="1" wire:model="pricing.limite_proveedor" /><x-select label="Alcance del límite" wire:model="pricing.alcance_limite" :options="[['id'=>'venta','name'=>'Por venta'],['id'=>'semana_jueves_miercoles','name'=>'Por semana de jueves a miércoles']]" /><x-textarea label="Motivo del cambio" wire:model="ruleReason" /><x-slot:actions><x-button label="Guardar nueva versión" type="submit" spinner="savePricing" /></x-slot:actions></x-form></x-card>
    <x-card title="Ajuste de inventario" shadow><x-form wire:submit="adjustStock"><x-select label="Tipo de queso" wire:model="adjustment.tipo" :options="$types" /><x-input label="Variación de moldes (+ ingreso / − salida)" type="number" step="1" wire:model="adjustment.delta" /><x-textarea label="Motivo obligatorio" wire:model="adjustment.motivo" /><x-slot:actions><x-button label="Registrar ajuste" type="submit" spinner="adjustStock" /></x-slot:actions></x-form></x-card>
    <x-card title="Movimientos de inventario" shadow><div class="overflow-x-auto"><table class="table"><thead><tr><th>Fecha</th><th>Tipo</th><th>Movimiento</th><th>Variación</th><th>Anterior → Nuevo</th><th>Motivo</th></tr></thead><tbody>@forelse($movements as $movement)<tr wire:key="movimiento-{{ $movement->id }}"><td>{{ $movement->created_at->format('d/m/Y H:i') }}</td><td>{{ str_replace('_',' ',$movement->tipo) }}</td><td>{{ $movement->clase }}</td><td>{{ $movement->delta }}</td><td>{{ $movement->anterior }} → {{ $movement->nuevo }}</td><td>{{ $movement->motivo }}</td></tr>@empty<tr><td colspan="6">No hay movimientos. Al finalizar un lote se registrará su ingreso.</td></tr>@endforelse</tbody></table></div>{{ $movements->links() }}</x-card>
    <x-modal wire:model="modal" title="Nueva venta" box-class="max-w-3xl">@if($errors->any())<div class="alert alert-error"><ul>@foreach($errors->all() as $message)<li>{{ $message }}</li>@endforeach</ul></div>@endif<x-form wire:submit="save"><x-select label="Cliente" wire:model="form.cliente_id" :options="array_values(array_filter($clientes,fn($c)=>$c['activo']))" option-label="nombre" placeholder="Seleccionar" /><x-input label="Fecha y hora" type="datetime-local" wire:model="form.vendida_at" />@foreach($form['detalles']??[] as $index=>$line)<div class="flex flex-wrap gap-3" wire:key="form-line-{{ $index }}"><x-select label="Tipo" wire:model="form.detalles.{{ $index }}.tipo" :options="$types" /><x-input label="Moldes" type="number" min="1" step="1" wire:model="form.detalles.{{ $index }}.moldes" /><x-button label="Retirar fila" wire:click="removeDetail({{ $index }})" /></div>@endforeach<x-button label="Añadir otro tipo" wire:click="addDetail" /><x-input label="Descuento total (S/)" type="number" step="0.01" min="0" wire:model="form.descuento" /><x-checkbox label="Descontar de liquidación del productor" wire:model="form.descontar_liquidacion" /><x-textarea label="Observaciones" wire:model="form.observaciones" /><p>Los precios y totales se calcularán al guardar. El stock se descontará al confirmar.</p><x-slot:actions><x-button label="Cancelar" @click="$wire.modal=false" /><x-button label="Guardar borrador" type="submit" spinner="save" class="btn-primary" /></x-slot:actions></x-form></x-modal>
</div>
