<?php
use App\Application\Recepciones\{ConsultarRecepciones, GestionarRecepciones};
use App\Infrastructure\Acopios\JornadaAcopio;
use App\Infrastructure\Rutas\RutaAcopio;
use App\Models\User;
use Illuminate\Support\Facades\Gate;
use Illuminate\Validation\ValidationException;
use Livewire\Component;
use Livewire\WithPagination;
use Mary\Traits\Toast;

new class extends Component {
    use WithPagination, Toast;
    public string $resultado = ''; public string $rutaId = ''; public string $recolectorId = ''; public string $desde = ''; public string $hasta = '';
    public bool $modal = false; public ?int $detalleId = null; public ?int $correccionId = null; public string $tolerancia = ''; public string $litrosPlanta = ''; public string $motivo = ''; public string $comentario = '';
    public array $form = ['jornada_id' => '', 'litros_planta' => '', 'recibida_at' => '', 'fuente_medicion' => 'manual', 'observaciones' => ''];
    public function boot(): void { Gate::authorize('administrar-recepciones'); }
    public function updatedResultado(): void { $this->resetPage(); } public function updatedRutaId(): void { $this->resetPage(); } public function updatedRecolectorId(): void { $this->resetPage(); }
    public function create(): void { $this->reset('form'); $this->form['recibida_at'] = now()->format('Y-m-d\TH:i'); $this->resetValidation(); $this->modal = true; }
    public function show(int $id): void { $this->detalleId = $id; $this->resetValidation(); }
    public function closeDetail(): void { $this->detalleId = null; $this->correccionId = null; $this->resetValidation(); }
    public function saveTolerance(): void { try { app(GestionarRecepciones::class)->saveTolerance(auth()->id(), $this->tolerancia); $this->success('Tolerancia guardada.'); } catch (ValidationException $e) { $this->fillErrors($e); } }
    public function save(): void { try { app(GestionarRecepciones::class)->create(auth()->id(), $this->form); $this->modal = false; $this->success('Recepción registrada y conciliada.'); } catch (ValidationException $e) { $this->fillErrors($e); } }
    public function edit(int $id, string $litros): void { $this->correccionId = $id; $this->litrosPlanta = $litros; $this->motivo = ''; $this->resetValidation(); }
    public function correct(): void { try { app(GestionarRecepciones::class)->correct(auth()->id(), $this->correccionId, ['litros_planta' => $this->litrosPlanta, 'motivo' => $this->motivo]); $this->correccionId = null; $this->success('Recepción corregida y auditada.'); } catch (ValidationException $e) { $this->fillErrors($e); } }
    public function annul(): void { try { app(GestionarRecepciones::class)->annul(auth()->id(), $this->detalleId, $this->motivo); $this->motivo = ''; $this->success('Recepción anulada.'); } catch (ValidationException $e) { $this->fillErrors($e); } }
    public function resolve(int $alertId): void { try { app(GestionarRecepciones::class)->resolveAlert(auth()->id(), $alertId, $this->comentario); $this->comentario = ''; $this->success('Alerta resuelta.'); } catch (ValidationException $e) { $this->fillErrors($e); } }
    private function fillErrors(ValidationException $e): void { $this->resetValidation(); foreach ($e->errors() as $field => $messages) { $this->addError($field, $messages[0]); } $this->error(collect($e->errors())->flatten()->first()); }
    public function with(): array { $filters = ['resultado' => $this->resultado, 'ruta_id' => $this->rutaId ?: null, 'recolector_id' => $this->recolectorId ?: null, 'desde' => $this->desde ?: null, 'hasta' => $this->hasta ?: null]; return ['recepciones' => app(ConsultarRecepciones::class)->list(auth()->id(), $filters), 'detalle' => $this->detalleId ? app(ConsultarRecepciones::class)->find(auth()->id(), $this->detalleId) : null, 'alertas' => app(ConsultarRecepciones::class)->pendingAlerts(auth()->id()), 'toleranciaActual' => app(ConsultarRecepciones::class)->tolerance(auth()->id()), 'rutas' => RutaAcopio::query()->orderBy('codigo')->get(['id', 'codigo', 'nombre'])->map(fn ($r) => ['id' => $r->id, 'name' => $r->codigo.' — '.$r->nombre])->all(), 'recolectores' => User::query()->whereHas('roles', fn ($q) => $q->where('name', 'recolector')->where('guard_name', 'web'))->orderBy('name')->get(['id', 'name'])->all(), 'jornadas' => JornadaAcopio::query()->where('estado', 'cerrada')->with('ruta')->latest('fecha_operativa')->limit(100)->get()->map(fn ($j) => ['id' => $j->id, 'name' => $j->ruta->codigo.' — '.$j->fecha_operativa->toDateString().' — '.$j->turno])->all(), 'headers' => [['key' => 'fecha_operativa', 'label' => 'Fecha'], ['key' => 'turno', 'label' => 'Turno'], ['key' => 'ruta', 'label' => 'Ruta'], ['key' => 'recolector', 'label' => 'Recolector'], ['key' => 'litros_campo', 'label' => 'Campo'], ['key' => 'litros_planta', 'label' => 'Planta'], ['key' => 'diferencia_litros', 'label' => 'Diferencia'], ['key' => 'resultado', 'label' => 'Resultado']]]; }
}; ?>

<div class="space-y-6">
    <x-header title="Recepción en planta" subtitle="Conciliación contra el acopio registrado en campo" separator progress-indicator><x-slot:actions><x-button label="Nueva recepción" icon="o-plus" wire:click="create" class="btn-primary" /></x-slot:actions></x-header>
    <x-card title="Tolerancia técnica" subtitle="Se copia en cada recepción y no tiene valor predeterminado" shadow><x-form wire:submit="saveTolerance"><div class="flex gap-3 items-end"><x-input label="Tolerancia (%)" type="number" step="0.001" wire:model="tolerancia" placeholder="Sin definir" /><span class="text-sm">Actual: {{ $toleranciaActual === null ? 'Sin definir' : $toleranciaActual.'%' }}</span><x-button label="Guardar tolerancia" type="submit" class="btn-primary" /></div></x-form></x-card>
    <x-card shadow><div class="grid grid-cols-1 md:grid-cols-3 xl:grid-cols-5 gap-4"><x-input label="Desde" type="date" wire:model.live="desde" /><x-input label="Hasta" type="date" wire:model.live="hasta" /><x-select label="Ruta" :options="$rutas" option-value="id" wire:model.live="rutaId" placeholder="Todas" placeholder-value="" /><x-select label="Recolector" :options="$recolectores" option-value="id" wire:model.live="recolectorId" placeholder="Todos" placeholder-value="" /><x-select label="Resultado" :options="[['id'=>'dentro_tolerancia','name'=>'Dentro de tolerancia'],['id'=>'con_diferencia','name'=>'Con diferencia'],['id'=>'anulada','name'=>'Anulada']]" wire:model.live="resultado" placeholder="Todos" placeholder-value="" /></div><div class="overflow-x-auto mt-5"><x-table :headers="$headers" :rows="$recepciones" with-pagination>@scope('cell_resultado', $r)<span class="badge {{ $r['resultado']==='con_diferencia'?'badge-warning':($r['resultado']==='anulada'?'badge-error':'badge-success') }}">{{ str_replace('_',' ',ucfirst($r['resultado'])) }}</span>@endscope @scope('actions', $r)<x-button label="Consultar" wire:click="show({{ $r['id'] }})" class="btn-ghost btn-sm" />@endscope <x-slot:empty><div class="p-8 text-center">No se encontraron recepciones.</div></x-slot:empty></x-table></div></x-card>
    <x-card title="Alertas pendientes" shadow>@forelse($alertas as $a)<div class="alert alert-warning mb-2" wire:key="alerta-{{ $a['id'] }}"><div><p>Diferencia: {{ $a['diferencia_litros'] }} L ({{ $a['diferencia_porcentaje'] }}%). Campo {{ $a['litros_campo'] }} L / planta {{ $a['litros_planta'] }} L.</p><x-input label="Comentario de resolución" wire:model="comentario" /><x-button label="Resolver" wire:click="resolve({{ $a['id'] }})" class="btn-primary btn-sm" /></div></div>@empty<p>No hay alertas pendientes.</p>@endforelse</x-card>
    @if($detalle)<x-card :title="$detalle['ruta'].' · '.$detalle['fecha_operativa']" shadow><div class="space-y-4"><div class="flex justify-between"><span class="badge">{{ str_replace('_',' ',ucfirst($detalle['resultado'])) }}</span><x-button label="Cerrar detalle" wire:click="closeDetail" class="btn-ghost btn-sm" /></div><p>Campo: <strong>{{ $detalle['litros_campo'] }} L</strong> · Planta: <strong>{{ $detalle['litros_planta'] }} L</strong> · Diferencia: {{ $detalle['diferencia_litros'] }} L ({{ $detalle['diferencia_porcentaje'] }}%) · Tolerancia usada: {{ $detalle['tolerancia_porcentaje'] }}%</p><p>Fuente: {{ $detalle['fuente_medicion'] }} · Recibida: {{ $detalle['recibida_at'] }}</p>@if($detalle['resultado']!=='anulada')<div class="flex gap-2"><x-button label="Corregir litros" wire:click="edit({{ $detalle['id'] }}, '{{ $detalle['litros_planta'] }}')" class="btn-primary btn-sm" /><x-button label="Anular recepción" wire:click="annul" class="btn-error btn-sm" /></div><x-textarea label="Motivo de corrección o anulación" wire:model="motivo" />@endif @if($correccionId)<x-form wire:submit="correct"><x-input label="Litros medidos nuevos" type="number" step="0.001" wire:model="litrosPlanta" /><x-slot:actions><x-button label="Guardar corrección" type="submit" class="btn-primary" /></x-slot:actions></x-form>@endif</div></x-card>@endif
    <x-modal wire:model="modal" title="Nueva recepción"><x-form wire:submit="save"><x-select label="Jornada cerrada" :options="$jornadas" option-value="id" wire:model="form.jornada_id" placeholder="Selecciona una jornada" /><x-input label="Litros medidos en planta" type="number" step="0.001" wire:model="form.litros_planta" /><x-input label="Fecha y hora de recepción" type="datetime-local" wire:model="form.recibida_at" /><x-select label="Fuente" :options="[['id'=>'manual','name'=>'Manual'],['id'=>'sensor','name'=>'Sensor']]" wire:model="form.fuente_medicion" /><x-textarea label="Observaciones" wire:model="form.observaciones" /><x-slot:actions><x-button label="Guardar" type="submit" class="btn-primary" spinner="save" /></x-slot:actions></x-form></x-modal>
</div>
