<?php
use App\Application\Ranking\GestionarRanking;
use App\Application\Ranking\ConsultarRanking;
use App\Application\Operacion\ReglasOperativas;
use Illuminate\Support\Facades\Gate;
use Illuminate\Validation\ValidationException;
use Livewire\Component;
use Livewire\WithPagination;
use Livewire\Attributes\Locked;
use Mary\Traits\Toast;
new class extends Component {
 use WithPagination,Toast;
 public array $form=['activo'=>false,'privacidad'=>'codigo','agregacion'=>'media','inicio_semana'=>'jueves','motivo'=>'','bandas'=>[]];
 public array $calculation=['tipo'=>'diario','fecha'=>'','ruta_id'=>null,'motivo'=>''];
 #[Locked] public ?string $selected=null;
 public function boot(): void { Gate::authorize('administrar-ranking'); }
 public function mount(): void { $current=app(ReglasOperativas::class)->current('ranking'); if($current['version']>0) { $this->form=array_intersect_key($current['valores'],$this->form)+$this->form; } foreach(GestionarRanking::CAMPOS as $key=>$field) { $this->form['bandas'][$key]??=[['minimo'=>'','maximo'=>'','puntos'=>'']]; } $this->calculation['fecha']=today()->toDateString(); }
 public function addBand(string $key): void { Gate::authorize('administrar-ranking'); abort_unless(isset(GestionarRanking::CAMPOS[$key]),422); if(count($this->form['bandas'][$key])<100) { $this->form['bandas'][$key][]=['minimo'=>'','maximo'=>'','puntos'=>'']; } }
 public function removeBand(string $key,int $index): void { Gate::authorize('administrar-ranking'); abort_unless(isset(GestionarRanking::CAMPOS[$key]),422); unset($this->form['bandas'][$key][$index]); $this->form['bandas'][$key]=array_values($this->form['bandas'][$key]); }
 public function saveRules(): void { Gate::authorize('administrar-ranking'); $this->perform(function(): void { app(GestionarRanking::class)->configure(auth()->id(),$this->form); $this->success('Nueva versión de puntuación guardada.'); }); }
 public function calculate(): void { Gate::authorize('administrar-ranking'); $this->perform(function(): void { $run=app(GestionarRanking::class)->calculate(auth()->id(),$this->calculation); $this->selected=$run->uuid; $this->success('Cálculo guardado.'); }); }
 public function show(string $uuid): void { Gate::authorize('administrar-ranking'); app(ConsultarRanking::class)->detail(auth()->id(),$uuid); $this->selected=$uuid; }
 private function perform(Closure $op): void { $this->resetValidation(); try { $op(); } catch(ValidationException $e) { foreach($e->errors() as $key=>$messages) { $this->addError($key,$messages[0]); } } catch(\Illuminate\Auth\Access\AuthorizationException $e) { throw $e; } catch(Throwable $e) { report($e); $this->addError('operacion','No se pudo completar la operación. Puedes reintentar.'); } }
 public function with(): array { $q=app(ConsultarRanking::class); return ['records'=>$q->history(auth()->id()),'detail'=>$this->selected?$q->detail(auth()->id(),$this->selected):null,'rutas'=>$q->routes(),'fields'=>GestionarRanking::CAMPOS,'rule'=>app(ReglasOperativas::class)->current('ranking')]; }
}; ?>
<div class="space-y-6"><x-header title="Ranking de calidad" subtitle="Criterios versionados y cálculos históricos" separator><x-slot:actions><x-button label="Ver Muro de Honor" :link="route('ranking.honor')" icon="o-trophy" /></x-slot:actions></x-header>
 @if($errors->any())<div class="alert alert-error" role="alert"><ul>@foreach($errors->all() as $message)<li>{{ $message }}</li>@endforeach</ul></div>@endif
 <x-card title="Calcular periodo" shadow><p>Solo se calculan puntos con criterios configurados. Agua añadida mayor a cero implica puntuación cero del productor para todo el periodo.</p><x-form wire:submit="calculate"><div class="grid md:grid-cols-3 gap-3"><x-select label="Periodo" wire:model="calculation.tipo" :options="[['id'=>'diario','name'=>'Diario'],['id'=>'semanal','name'=>'Semanal'],['id'=>'mensual','name'=>'Mensual']]" /><x-input label="Fecha del periodo" type="date" wire:model="calculation.fecha" /><x-select label="Ruta" wire:model="calculation.ruta_id" :options="$rutas" placeholder="Todas" /></div><x-textarea label="Motivo del cálculo o recálculo" wire:model="calculation.motivo" /><x-slot:actions><x-button label="Calcular y guardar" type="submit" spinner="calculate" class="btn-primary" /></x-slot:actions></x-form></x-card>
 <x-card title="Cálculos históricos" shadow><div class="overflow-x-auto"><table class="table"><thead><tr><th>Periodo</th><th>Versión</th><th>Resultados</th><th>Vigencia</th><th></th></tr></thead><tbody>@forelse($records as $r)<tr wire:key="calculo-{{ $r->id }}"><td>{{ $r->tipo }}: {{ $r->desde->format('d/m/Y') }} — {{ $r->hasta->format('d/m/Y') }}</td><td>{{ $r->regla_aplicada['version'] }}</td><td>{{ $r->resultados_count }}</td><td>{{ $r->vigente?'Vigente':'Sustituido o requiere recálculo' }}</td><td><x-button label="Consultar" wire:click="show('{{ $r->uuid }}')" class="btn-sm" /></td></tr>@empty<tr><td colspan="5">No hay cálculos. Configura criterios aprobados y registra mediciones completas.</td></tr>@endforelse</tbody></table></div>{{ $records->links() }}</x-card>
 @if($detail)<x-card :title="'Cálculo '.$detail->uuid" shadow><p>Algoritmo {{ $detail->algoritmo }} · Versión {{ $detail->regla_aplicada['version'] }}.</p><div class="overflow-x-auto"><table class="table"><thead><tr><th>Posición</th><th>Productor</th><th>Puntos</th><th>Explicación</th></tr></thead><tbody>@foreach($detail->resultados as $row)<tr wire:key="resultado-{{ $row->id }}"><td>{{ $row->posicion ?? 'Pendiente' }}</td><td>{{ $row->productor_snapshot['codigo'] }} — {{ $row->productor_snapshot['nombres'] }} {{ $row->productor_snapshot['apellidos'] }}</td><td>{{ $row->puntuacion ?? 'Sin datos completos' }}</td><td>@if($row->detalle['agua_anadida'])Agua añadida: puntuación cero.@endif {{ implode('; ',$row->detalle['faltantes']) }}<details><summary>Ver parámetros y puntos</summary><pre class="text-xs overflow-x-auto">{{ json_encode($row->detalle,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre></details></td></tr>@endforeach</tbody></table></div></x-card>@endif
 <x-card title="Criterios de puntuación" shadow><p>Versión actual {{ $rule['version'] }}. No hay bandas científicas predefinidas. El administrador debe registrar criterios aprobados: mínimo incluido, máximo excluido, salvo el último máximo incluido. Cubrir el dominio completo sin huecos ni solapamientos.</p><x-form wire:submit="saveRules"><x-checkbox label="Habilitar ranking público" wire:model="form.activo" /><div class="grid md:grid-cols-3 gap-3"><x-select label="Identidad pública" wire:model="form.privacidad" :options="[['id'=>'codigo','name'=>'Código del productor'],['id'=>'nombre_abreviado','name'=>'Nombre abreviado'],['id'=>'nombre_completo','name'=>'Nombre completo']]" /><x-select label="Agregación de análisis" wire:model="form.agregacion" :options="[['id'=>'media','name'=>'Media de puntuaciones'],['id'=>'minimo','name'=>'Menor puntuación']]" /><x-select label="Inicio de semana" wire:model="form.inicio_semana" :options="[['id'=>'jueves','name'=>'Jueves'],['id'=>'lunes','name'=>'Lunes']]" /></div>
 @foreach($fields as $key=>$field)<div class="border border-base-300 rounded-lg p-4 space-y-3" wire:key="criterio-{{ $key }}"><h3 class="font-semibold">{{ $field[0] }} · {{ $field[1] }} · Peso {{ $field[3] }} %</h3><p>Dominio de captura 0–{{ $field[2] }}, no rango sanitario.</p>@foreach($form['bandas'][$key]??[] as $index=>$band)<div class="grid md:grid-cols-4 gap-3" wire:key="banda-{{ $key }}-{{ $index }}"><x-input label="Mínimo" type="number" step="0.0001" wire:model="form.bandas.{{ $key }}.{{ $index }}.minimo" /><x-input label="Máximo" type="number" step="0.0001" wire:model="form.bandas.{{ $key }}.{{ $index }}.maximo" /><x-input label="Puntos (0–100)" type="number" step="0.0001" wire:model="form.bandas.{{ $key }}.{{ $index }}.puntos" /><x-button label="Retirar banda" wire:click="removeBand('{{ $key }}',{{ $index }})" /></div>@endforeach<x-button label="Añadir banda" wire:click="addBand('{{ $key }}')" /></div>@endforeach
 <x-textarea label="Motivo y referencia de aprobación de criterios" wire:model="form.motivo" /><x-slot:actions><x-button label="Guardar versión de criterios" type="submit" spinner="saveRules" /></x-slot:actions></x-form></x-card>
</div>
