<?php
use App\Application\Traslados\GestionarTraslados;
use App\Application\Traslados\ConsultarTraslados;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use Livewire\Component;
use Livewire\WithPagination;
use Livewire\Attributes\Locked;
use Mary\Traits\Toast;
new class extends Component {
 use WithPagination,Toast;
 public string $state=''; public array $form=[]; public bool $modal=false; public string $comment=''; public array $configuration=['anticipacion_dias'=>'','motivo'=>''];
 #[Locked] public ?string $selected=null;
 public function boot(): void { Gate::authorize('administrar-traslados'); }
 public function updatedState(): void { Gate::authorize('administrar-traslados'); $this->resetPage(); }
 public function create(): void { Gate::authorize('administrar-traslados'); $this->resetValidation(); $this->form=['uuid'=>(string)Str::uuid(),'productor_id'=>'','ruta_solicitada_id'=>'','fecha_efectiva'=>'','motivo'=>'']; $this->modal=true; }
 public function show(string $uuid): void { Gate::authorize('administrar-traslados'); app(ConsultarTraslados::class)->find(auth()->id(),$uuid); $this->selected=$uuid; $this->comment=''; $this->resetValidation(); }
 public function save(): void { Gate::authorize('administrar-traslados'); $this->perform(function(): void { $r=app(GestionarTraslados::class)->request(auth()->id(),$this->form); $this->show($r->uuid); $this->modal=false; $this->success('Solicitud registrada.'); }); }
 public function runAction(string $action): void { Gate::authorize('administrar-traslados'); $this->perform(function() use($action): void { $s=app(GestionarTraslados::class); match($action) { 'aprobar'=>$s->decide(auth()->id(),$this->selected,true,$this->comment),'rechazar'=>$s->decide(auth()->id(),$this->selected,false,$this->comment),'cancelar'=>$s->cancel(auth()->id(),$this->selected,$this->comment),'aplicar'=>$s->apply(auth()->id(),$this->selected),default=>abort(404) }; $this->success('Operación registrada.'); }); }
 public function saveConfiguration(): void { Gate::authorize('administrar-traslados'); $this->perform(function(): void { app(GestionarTraslados::class)->configuration(auth()->id(),$this->configuration); $this->success('Configuración versionada guardada.'); }); }
 private function perform(Closure $op): void { $this->resetValidation(); try { $op(); } catch(ValidationException $e) { foreach($e->errors() as $key=>$messages) { $this->addError($key,$messages[0]); } } catch(\Illuminate\Auth\Access\AuthorizationException $e) { throw $e; } catch(Throwable $e) { report($e); $this->addError('operacion','No se pudo completar la operación. Puedes reintentar.'); } }
 public function with(): array { $q=app(ConsultarTraslados::class); return $q->options(auth()->id())+['records'=>$q->listing(auth()->id(),$this->state),'detail'=>$this->selected?$q->find(auth()->id(),$this->selected):null,'audit'=>$this->selected?$q->audit(auth()->id(),$this->selected):[]]; }
}; ?>
<div class="space-y-6">
 <x-header title="Solicitudes de traslado" subtitle="Cambios de ruta solicitados, aprobados y auditados" separator><x-slot:actions><x-button label="Nueva solicitud" wire:click="create" class="btn-primary" icon="o-plus" /></x-slot:actions></x-header>
 @if($errors->any())<div class="alert alert-error" role="alert"><ul>@foreach($errors->all() as $message)<li>{{ $message }}</li>@endforeach</ul></div>@endif
 @if($regla['valores']['anticipacion_dias']===null)<div class="alert alert-warning">Define la anticipación mínima antes de registrar solicitudes.</div>@endif
 <x-card shadow><x-select label="Estado" wire:model.live="state" :options="[['id'=>'pendiente','name'=>'Pendiente'],['id'=>'aprobada','name'=>'Aprobada'],['id'=>'rechazada','name'=>'Rechazada'],['id'=>'aplicada','name'=>'Aplicada'],['id'=>'cancelada','name'=>'Cancelada']]" placeholder="Todos" /><div class="overflow-x-auto"><table class="table"><thead><tr><th>Productor</th><th>Ruta anterior → solicitada</th><th>Fecha efectiva</th><th>Estado</th><th></th></tr></thead><tbody>@forelse($records as $r)<tr wire:key="traslado-{{ $r->id }}"><td>{{ $r->productor->codigo }} — {{ $r->productor->nombres }} {{ $r->productor->apellidos }}</td><td>{{ $r->actual->codigo }} → {{ $r->solicitada->codigo }}</td><td>{{ $r->fecha_efectiva->format('d/m/Y') }}</td><td>{{ $r->estado }} @if($r->ultimo_error)<span class="badge badge-warning">Conflicto pendiente</span>@endif</td><td><x-button label="Consultar" wire:click="show('{{ $r->uuid }}')" class="btn-sm" /></td></tr>@empty<tr><td colspan="5">No hay solicitudes para este filtro.</td></tr>@endforelse</tbody></table></div>{{ $records->links() }}</x-card>
 @if($detail)<x-card :title="'Solicitud '.$detail->uuid" shadow><p>Productor {{ $detail->productor->codigo }} · {{ $detail->actual->nombre }} → {{ $detail->solicitada->nombre }}</p><p>Solicitada: {{ $detail->solicitada_at->format('d/m/Y H:i') }}. Efectiva: {{ $detail->fecha_efectiva->format('d/m/Y') }}.</p><p>Motivo: {{ $detail->motivo }}</p><p>Estado: {{ $detail->estado }}. Anticipación aplicada: {{ $detail->regla_aplicada['valores']['anticipacion_dias'] }} días (versión {{ $detail->regla_aplicada['version'] }}).</p><p>Decisión: {{ $detail->comentario }} · {{ $detail->decidida_at?->format('d/m/Y H:i') }}</p>@if($detail->ultimo_error)<p class="text-warning">{{ $detail->ultimo_error }}</p>@endif
 @if(in_array($detail->estado,['pendiente','aprobada']))<x-textarea label="Comentario obligatorio para decisión o cancelación" wire:model="comment" /><div class="flex flex-wrap gap-3 mt-3">@if($detail->estado==='pendiente')<x-button label="Aprobar" wire:click="runAction('aprobar')" spinner="runAction" class="btn-primary" /><x-button label="Rechazar" wire:click="runAction('rechazar')" spinner="runAction" />@else<x-button label="Aplicar traslado aprobado" wire:click="runAction('aplicar')" spinner="runAction" class="btn-primary" />@endif<x-button label="Cancelar solicitud" wire:click="runAction('cancelar')" spinner="runAction" class="btn-error" /></div>@endif
 <h3 class="font-semibold mt-4">Historial</h3>@foreach($audit as $item)<details wire:key="audit-{{ $item['id'] }}"><summary>{{ $item['accion'] }} · {{ $item['usuario']['name'] }} · {{ $item['created_at'] }} · {{ $item['motivo'] }}</summary><pre class="overflow-x-auto text-xs">{{ json_encode(['anterior'=>$item['anteriores'],'nuevo'=>$item['nuevos']],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre></details>@endforeach</x-card>@endif
 <x-card title="Anticipación de solicitudes" shadow><p>Versión {{ $regla['version'] }}. Mínimo actual: {{ $regla['valores']['anticipacion_dias'] ?? 'Sin definir' }} días calendario. Cambiar la configuración no altera solicitudes previas.</p><x-form wire:submit="saveConfiguration"><x-input label="Días mínimos" type="number" min="1" max="365" step="1" wire:model="configuration.anticipacion_dias" /><x-textarea label="Motivo de configuración" wire:model="configuration.motivo" /><x-slot:actions><x-button label="Guardar nueva versión" type="submit" spinner="saveConfiguration" /></x-slot:actions></x-form></x-card>
 <x-modal wire:model="modal" title="Solicitar traslado">@if($errors->any())<div class="alert alert-error"><ul>@foreach($errors->all() as $message)<li>{{ $message }}</li>@endforeach</ul></div>@endif<x-form wire:submit="save"><x-select label="Productor con ruta actual" wire:model="form.productor_id" :options="$productores" placeholder="Seleccionar" /><x-select label="Ruta solicitada" wire:model="form.ruta_solicitada_id" :options="$rutas" placeholder="Seleccionar" /><x-input label="Fecha efectiva" type="date" wire:model="form.fecha_efectiva" /><x-textarea label="Motivo" wire:model="form.motivo" /><p>La ruta actual se obtiene del servidor. Aprobar no cambia la asignación hasta la fecha efectiva.</p><x-slot:actions><x-button label="Cancelar" @click="$wire.modal=false" /><x-button label="Guardar solicitud" type="submit" spinner="save" class="btn-primary" /></x-slot:actions></x-form></x-modal>
</div>
