<?php
use App\Application\Liquidaciones\{ConsultarLiquidaciones,GestionarLiquidaciones,GestionarPeriodos,CalcularLiquidaciones};
use App\Application\Operacion\ReglasOperativas;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use Livewire\Component;
use Livewire\WithPagination;
use Livewire\Attributes\Locked;
use Mary\Traits\Toast;
new class extends Component {
 use WithPagination,Toast;
 public string $search=''; public string $state=''; public string $periodFilter=''; public string $reason='';
 public array $periodForm=['uuid'=>'','desde'=>'','motivo'=>''];
 public array $adjustForm=['uuid'=>'','tipo'=>'ajuste','importe'=>'','origen_uuid'=>'','motivo'=>''];
 public array $payForm=['uuid_externo'=>'','metodo'=>'','pagado_at'=>''];
 public array $ruleForm=['precio_litro'=>'','conflicto_tarifas'=>'bloquear','perdida_incluye_bonos'=>null,'motivo'=>''];
 #[Locked] public ?string $selected=null;
 public function boot(): void { Gate::authorize('operar-liquidaciones'); }
 public function mount(): void { $this->periodForm['uuid']=(string)Str::uuid(); }
 public function updatedSearch(): void { Gate::authorize('operar-liquidaciones'); $this->resetPage(); }
 public function updatedState(): void { Gate::authorize('operar-liquidaciones'); $this->resetPage(); }
 public function show(string $uuid): void { Gate::authorize('operar-liquidaciones'); app(ConsultarLiquidaciones::class)->find(auth()->id(),$uuid); $this->selected=$uuid; $this->adjustForm['uuid']=(string)Str::uuid(); $this->payForm=['uuid_externo'=>(string)Str::uuid(),'metodo'=>'','pagado_at'=>now()->format('Y-m-d\TH:i:s')]; $this->resetValidation(); }
 public function createPeriod(): void { Gate::authorize('administrar-liquidaciones'); $this->perform(function(): void { app(GestionarPeriodos::class)->create(auth()->id(),$this->periodForm); $this->periodForm['uuid']=(string)Str::uuid(); }); }
 public function periodAction(string $uuid,string $action): void { Gate::authorize($action==='calcular'?'operar-liquidaciones':'administrar-liquidaciones'); $this->perform(function() use($uuid,$action): void { match($action) { 'cerrar'=>app(GestionarPeriodos::class)->close(auth()->id(),$uuid,$this->reason),'calcular'=>app(CalcularLiquidaciones::class)->calculate(auth()->id(),$uuid,$this->reason),'aprobar'=>app(GestionarLiquidaciones::class)->approve(auth()->id(),$uuid,$this->reason),'anular'=>app(GestionarPeriodos::class)->annul(auth()->id(),$uuid,$this->reason),default=>abort(404) }; }); }
 public function adjust(): void { Gate::authorize('operar-liquidaciones'); $this->perform(function(): void { app(GestionarLiquidaciones::class)->adjustment(auth()->id(),$this->selected??'',$this->adjustForm); $this->adjustForm['uuid']=(string)Str::uuid(); }); }
 public function decide(string $uuid,string $decision): void { Gate::authorize('administrar-liquidaciones'); $this->perform(fn()=>app(GestionarLiquidaciones::class)->decideAdjustment(auth()->id(),$uuid,['decision'=>$decision,'motivo'=>$this->reason])); }
 public function pay(): void { Gate::authorize('operar-liquidaciones'); $this->perform(fn()=>app(GestionarLiquidaciones::class)->pay(auth()->id(),$this->selected??'',$this->payForm)); }
 public function saveRules(): void { Gate::authorize('administrar-liquidaciones'); $this->perform(fn()=>app(GestionarPeriodos::class)->configure(auth()->id(),$this->ruleForm)); }
 private function perform(Closure $operation): void { $this->resetValidation(); try { $operation(); $this->success('Operación registrada.'); } catch(ValidationException $e) { foreach($e->errors() as $key=>$messages) { $this->addError($key,$messages[0]); } } catch(\Illuminate\Auth\Access\AuthorizationException $e) { throw $e; } catch(Throwable $e) { report($e); $this->addError('operacion','No se pudo completar la operación. Puedes reintentar.'); } }
 public function with(): array { $q=app(ConsultarLiquidaciones::class); $detail=$this->selected?$q->find(auth()->id(),$this->selected):null; return ['records'=>$q->listing(auth()->id(),['buscar'=>$this->search,'estado'=>$this->state,'periodo'=>$this->periodFilter]),'periods'=>$q->periods(auth()->id()),'detail'=>$detail,'totals'=>$detail?app(GestionarLiquidaciones::class)->totals($detail):[],'rule'=>app(ReglasOperativas::class)->current('liquidaciones')]; }
}; ?>
<div class="space-y-6">
 <x-header title="Liquidaciones semanales" subtitle="Jueves a miércoles · pago previsto viernes" separator />
 @if($errors->any())<div class="alert alert-error" role="alert"><ul>@foreach($errors->all() as $message)<li>{{ $message }}</li>@endforeach</ul></div>@endif
 <x-card title="Periodos" shadow><p>El cierre conserva las fuentes y bloquea cambios de acopio. Revisa las sanciones antes de cerrar.</p><x-textarea label="Motivo de cierre, cálculo, aprobación, anulación o decisión de ajuste" wire:model="reason" />
 <div class="overflow-x-auto"><table class="table"><thead><tr><th>Desde / hasta</th><th>Pago previsto</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>@forelse($periods as $p)<tr wire:key="period-{{ $p->id }}"><td>{{ $p->desde->format('d/m/Y') }} — {{ $p->hasta->format('d/m/Y') }}</td><td>{{ $p->pago_previsto->format('d/m/Y') }}</td><td>{{ $p->estado }}</td><td class="flex flex-wrap gap-2">@can('administrar-liquidaciones')@if($p->estado==='abierto')<x-button label="Cerrar" wire:click="periodAction('{{ $p->uuid }}','cerrar')" spinner="periodAction" />@endif @if($p->estado==='calculado')<x-button label="Aprobar" wire:click="periodAction('{{ $p->uuid }}','aprobar')" spinner="periodAction" />@endif @if(!in_array($p->estado,['pagado','anulado']))<x-button label="Anular" wire:click="periodAction('{{ $p->uuid }}','anular')" spinner="periodAction" />@endif @endcan @if($p->estado==='cerrado')<x-button label="Calcular" wire:click="periodAction('{{ $p->uuid }}','calcular')" spinner="periodAction" />@endif</td></tr>@empty<tr><td colspan="4">No hay periodos. Un administrador puede crear el primero.</td></tr>@endforelse</tbody></table></div>{{ $periods->links() }}</x-card>
 @can('administrar-liquidaciones')<x-card title="Crear periodo" shadow><x-form wire:submit="createPeriod"><x-input label="Jueves inicial" type="date" wire:model="periodForm.desde" /><x-textarea label="Motivo" wire:model="periodForm.motivo" /><x-slot:actions><x-button label="Crear periodo" type="submit" spinner="createPeriod" class="btn-primary" /></x-slot:actions></x-form></x-card>@endcan
 <x-card title="Liquidaciones por productor" shadow><div class="grid md:grid-cols-2 gap-4"><x-input label="Buscar productor" wire:model.live.debounce.300ms="search" /><x-select label="Estado" wire:model.live="state" :options="[['id'=>'calculada','name'=>'Calculada'],['id'=>'aprobada','name'=>'Aprobada'],['id'=>'pagada','name'=>'Pagada'],['id'=>'anulada','name'=>'Anulada']]" placeholder="Todos" /></div><div class="overflow-x-auto"><table class="table"><thead><tr><th>Productor</th><th>Semana</th><th>Litros</th><th>Base S/</th><th>Estado</th><th></th></tr></thead><tbody>@forelse($records as $l)<tr wire:key="liq-{{ $l->id }}"><td>{{ implode(' ', $l->productor_snapshot) }}</td><td>{{ $l->periodo->desde->format('d/m/Y') }}</td><td>{{ $l->litros_total }}</td><td>{{ $l->total_base }}</td><td>{{ $l->estado }}</td><td><x-button label="Consultar" wire:click="show('{{ $l->uuid }}')" /></td></tr>@empty<tr><td colspan="6">No hay liquidaciones para los filtros indicados.</td></tr>@endforelse</tbody></table></div>{{ $records->links() }}</x-card>
 @if($detail)<x-card :title="'Liquidación '.$detail->uuid" shadow><p>{{ implode(' ', $detail->productor_snapshot) }} · {{ $detail->estado }}</p><div class="overflow-x-auto"><table class="table"><thead><tr><th>Día</th><th>Litros</th></tr></thead><tbody>@foreach($detail->litros_diarios as $day=>$liters)<tr><td>{{ $day }}</td><td>{{ $liters }}</td></tr>@endforeach</tbody></table></div><p>Precio base S/ {{ $detail->precio_litro }} · Bruto S/ {{ $detail->importe_bruto }} · Penalizaciones S/ {{ $detail->penalizaciones }} · Compras de queso S/ {{ $detail->descuentos_queso }}</p><p>Bonos S/ {{ $totals['bonos'] }} · Bonos retenidos S/ {{ $totals['bonos_retenidos'] }} · Ajustes S/ {{ $totals['ajustes'] }}</p><p class="font-bold text-xl">Total S/ {{ $totals['total'] }}</p>
 <div class="flex gap-3 my-3"><x-button label="Comprobante imprimible" :link="route('admin.liquidaciones.comprobante', $detail->uuid)" external /><x-button label="Descargar PDF" :link="route('admin.liquidaciones.pdf', $detail->uuid)" external /></div><h3 class="font-semibold mt-4">Ajustes y decisiones</h3>@forelse($detail->ajustes as $adjustment)<div class="border rounded p-3 my-2"><p>{{ $adjustment->tipo }} · S/ {{ $adjustment->importe }} · {{ $adjustment->estado }} · {{ $adjustment->motivo }} · {{ $adjustment->comentario }}</p>@can('administrar-liquidaciones')@if($adjustment->estado==='pendiente')<x-button label="Aprobar ajuste" wire:click="decide('{{ $adjustment->uuid }}','aprobado')" spinner="decide" /><x-button label="Rechazar ajuste" wire:click="decide('{{ $adjustment->uuid }}','rechazado')" spinner="decide" />@endif @endcan</div>@empty<p>Sin ajustes.</p>@endforelse
 @if(in_array($detail->estado,['calculada','aprobada']))<x-form wire:submit="adjust"><x-select label="Tipo" wire:model="adjustForm.tipo" :options="[['id'=>'ajuste','name'=>'Ajuste'],['id'=>'bono','name'=>'Bono']]" /><x-input label="Importe S/ (negativo para descuento)" wire:model="adjustForm.importe" /><x-input label="UUID de liquidación pagada anterior (opcional)" wire:model="adjustForm.origen_uuid" /><x-textarea label="Motivo del ajuste" wire:model="adjustForm.motivo" /><x-slot:actions><x-button label="Solicitar ajuste" type="submit" spinner="adjust" /></x-slot:actions></x-form>@endif
 @if($detail->estado==='aprobada')<x-form wire:submit="pay"><x-input label="Método de pago" wire:model="payForm.metodo" /><x-input label="Fecha y hora de pago" type="datetime-local" step="1" wire:model="payForm.pagado_at" /><x-slot:actions><x-button label="Registrar pago total" type="submit" spinner="pay" class="btn-primary" /></x-slot:actions></x-form>@endif @if($detail->pago)<p>Pagado: {{ $detail->pago->pagado_at->format('d/m/Y H:i') }} · {{ $detail->pago->metodo }} · S/ {{ $detail->pago->importe }}</p>@endif
 </x-card>@endif
 @can('administrar-liquidaciones')<x-card title="Tarifa y reglas versionadas" shadow><p>Versión {{ $rule['version'] }} · Precio S/ {{ $rule['valores']['precio_litro'] }}. Los cambios no alteran periodos cerrados.</p><x-form wire:submit="saveRules"><x-input label="Precio por litro S/" wire:model="ruleForm.precio_litro" /><x-select label="Tarifas penalizadas coincidentes" wire:model="ruleForm.conflicto_tarifas" :options="[['id'=>'bloquear','name'=>'Bloquear para revisión'],['id'=>'menor_tarifa','name'=>'Aplicar menor tarifa aprobada']]" /><x-select label="Pérdida de liquidación incluye bonos" wire:model="ruleForm.perdida_incluye_bonos" :options="[['id'=>1,'name'=>'Sí'],['id'=>0,'name'=>'No']]" placeholder="Pendiente de definición" /><x-textarea label="Motivo de nueva versión" wire:model="ruleForm.motivo" /><x-slot:actions><x-button label="Guardar versión" type="submit" spinner="saveRules" /></x-slot:actions></x-form></x-card>@endcan
</div>
