<?php
use App\Application\Comunicados\ConsultarComunicados;
use App\Application\Comunicados\GestionarComunicados;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use Livewire\Component;
use Livewire\WithPagination;
use Livewire\Attributes\Locked;
use Mary\Traits\Toast;
new class extends Component {
 use WithPagination,Toast;
 public string $search=''; public array $form=[]; public bool $modal=false; public string $motivo='';
 public array $link=['usuario_id'=>'','productor_id'=>'','activa'=>true,'motivo'=>''];
 #[Locked] public ?string $selected=null; #[Locked] public bool $editing=false;
 public function boot(): void { Gate::authorize('administrar-comunicados'); }
 public function updatedSearch(): void { Gate::authorize('administrar-comunicados'); $this->resetPage(); }
 public function create(): void { Gate::authorize('administrar-comunicados'); $this->resetValidation(); $this->editing=false; $this->form=['uuid'=>(string)Str::uuid(),'titulo'=>'','contenido'=>'','tipo'=>'general','audiencia'=>'todos_productores','ruta_id'=>null,'roles'=>[],'productores'=>[],'publicar_at'=>now()->format('Y-m-d\TH:i'),'vence_at'=>null]; $this->modal=true; }
 public function show(string $uuid): void { Gate::authorize('administrar-comunicados'); app(ConsultarComunicados::class)->detail(auth()->id(),$uuid); $this->selected=$uuid; $this->motivo=''; $this->resetValidation(); }
 public function edit(): void { Gate::authorize('administrar-comunicados'); $d=app(ConsultarComunicados::class)->detail(auth()->id(),$this->selected); $r=$d['record']; $this->form=$r->only(['uuid','titulo','contenido','tipo','audiencia','ruta_id']); $this->form+=['roles'=>$r->roles_destino,'productores'=>$d['productores'],'publicar_at'=>$r->publicar_at->format('Y-m-d\TH:i'),'vence_at'=>$r->vence_at?->format('Y-m-d\TH:i'),'motivo'=>'']; $this->editing=true; $this->modal=true; }
 public function save(): void { Gate::authorize('administrar-comunicados'); $this->perform(function(): void { $r=app(GestionarComunicados::class)->save(auth()->id(),$this->form,$this->editing?$this->selected:null); $this->show($r->uuid); $this->modal=false; $this->success('Comunicado guardado como borrador.'); }); }
 public function runAction(string $action): void { Gate::authorize('administrar-comunicados'); $this->perform(function() use($action): void { $s=app(GestionarComunicados::class); match($action) { 'publicar'=>$s->publish(auth()->id(),$this->selected),'anular'=>$s->annul(auth()->id(),$this->selected,$this->motivo),default=>abort(404) }; $this->success('Estado actualizado.'); }); }
 public function saveLink(): void { Gate::authorize('administrar-comunicados'); $this->perform(function(): void { app(GestionarComunicados::class)->link(auth()->id(),$this->link); $this->success('Vinculación guardada con auditoría.'); }); }
 private function perform(Closure $operation): void { $this->resetValidation(); try { $operation(); } catch(ValidationException $e) { foreach($e->errors() as $k=>$messages) { $this->addError($k,$messages[0]); } } catch(\Illuminate\Auth\Access\AuthorizationException $e) { throw $e; } catch(Throwable $e) { report($e); $this->addError('operacion','No se pudo completar la operación. Puedes reintentar.'); } }
 public function with(): array { $q=app(ConsultarComunicados::class); return $q->options(auth()->id())+['records'=>$q->management(auth()->id(),$this->search),'detail'=>$this->selected?$q->detail(auth()->id(),$this->selected):null]; }
}; ?>
<div class="space-y-6">
 <x-header title="Comunicados" subtitle="Publicaciones y programación para destinatarios autorizados" separator><x-slot:actions><x-button label="Nuevo comunicado" wire:click="create" icon="o-plus" class="btn-primary" /></x-slot:actions></x-header>
 @if($errors->any())<div class="alert alert-error" role="alert"><ul>@foreach($errors->all() as $message)<li>{{ $message }}</li>@endforeach</ul></div>@endif
 <x-card shadow><x-input label="Buscar título" wire:model.live.debounce="search" /><div class="overflow-x-auto"><table class="table"><thead><tr><th>Título</th><th>Tipo / audiencia</th><th>Publicación / vencimiento</th><th>Estado</th><th></th></tr></thead><tbody>@forelse($records as $r)<tr wire:key="comunicado-{{ $r->id }}"><td>{{ $r->titulo }}</td><td>{{ $r->tipo }} / {{ str_replace('_',' ',$r->audiencia) }}</td><td>{{ $r->publicar_at->format('d/m/Y H:i') }}<br>{{ $r->vence_at?->format('d/m/Y H:i') ?? 'Sin vencimiento' }}</td><td>{{ $r->visibleState() }}</td><td><x-button label="Consultar" wire:click="show('{{ $r->uuid }}')" class="btn-sm" /></td></tr>@empty<tr><td colspan="5">No hay comunicados. Crea un borrador y revisa su audiencia antes de publicarlo.</td></tr>@endforelse</tbody></table></div>{{ $records->links() }}</x-card>
 @if($detail)<x-card :title="$detail['record']->titulo" shadow><p class="whitespace-pre-wrap">{{ $detail['record']->contenido }}</p><p>Autor: {{ $detail['record']->autor->name }}. Estado: {{ $detail['record']->visibleState() }}.</p><p>Audiencia: {{ str_replace('_',' ',$detail['record']->audiencia) }}. Productores incluidos: {{ count($detail['productores']) }}. Roles: {{ implode(', ',$detail['record']->roles_destino) }}.</p>
 @if($detail['record']->estado==='borrador')<div class="flex gap-3 mt-3"><x-button label="Corregir borrador" wire:click="edit" /><x-button label="Publicar o programar" wire:click="runAction('publicar')" spinner="runAction" class="btn-primary" /></div>@endif
 @if($detail['record']->estado!=='anulado')<x-textarea label="Motivo de anulación" wire:model="motivo" /><x-button label="Anular comunicado" wire:click="runAction('anular')" spinner="runAction" class="btn-error mt-3" />@endif
 <h3 class="font-semibold mt-4">Lecturas (solo administración)</h3>@forelse($detail['lecturas'] as $read)<p>{{ $read->name }} · {{ $read->leida_at }}</p>@empty<p>Aún no hay lecturas.</p>@endforelse
 <h3 class="font-semibold mt-4">Historial</h3>@foreach($detail['audit'] as $item)<details wire:key="audit-{{ $item['id'] }}"><summary>{{ $item['accion'] }} · {{ $item['usuario']['name'] }} · {{ $item['created_at'] }} · {{ $item['motivo'] }}</summary><pre class="overflow-x-auto text-xs">{{ json_encode(['anterior'=>$item['anteriores'],'nuevo'=>$item['nuevos']],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre></details>@endforeach</x-card>@endif
 <x-card title="Vincular cuenta de productor" shadow><p>Primero crea o selecciona una cuenta real con rol productor en Usuarios. Una cuenta representa a un único productor. La vinculación se conserva y puede desactivarse; no se reasigna a otra persona.</p>@if(empty($cuentas))<p>No hay cuentas activas con rol productor.</p>@endif<x-form wire:submit="saveLink"><x-select label="Cuenta" wire:model="link.usuario_id" :options="$cuentas" placeholder="Seleccionar" /><x-select label="Productor" wire:model="link.productor_id" :options="$productores" placeholder="Seleccionar" /><x-checkbox label="Vinculación activa" wire:model="link.activa" /><x-textarea label="Motivo y comprobación de identidad" wire:model="link.motivo" /><x-slot:actions><x-button label="Guardar vinculación" type="submit" spinner="saveLink" /></x-slot:actions></x-form><ul>@foreach($vinculos as $v)<li wire:key="vinculo-{{ $v['usuario_id'] }}">{{ $v['name'] }} → {{ $v['codigo'] }} · {{ $v['activa']?'Activa':'Inactiva' }}</li>@endforeach</ul></x-card>
 <x-modal wire:model="modal" title="Datos del comunicado" box-class="max-w-3xl">@if($errors->any())<div class="alert alert-error"><ul>@foreach($errors->all() as $message)<li>{{ $message }}</li>@endforeach</ul></div>@endif<x-form wire:submit="save"><x-input label="Título" wire:model="form.titulo" /><x-textarea label="Contenido (texto plano)" wire:model="form.contenido" rows="6" /><x-select label="Tipo" wire:model="form.tipo" :options="[['id'=>'general','name'=>'General'],['id'=>'urgente','name'=>'Urgente'],['id'=>'capacitacion','name'=>'Capacitación']]" /><x-select label="Audiencia" wire:model.live="form.audiencia" :options="[['id'=>'todos_productores','name'=>'Todos los productores activos'],['id'=>'ruta','name'=>'Productores de una ruta'],['id'=>'seleccionados','name'=>'Productores seleccionados'],['id'=>'roles','name'=>'Roles internos seleccionados']]" />
 @if(($form['audiencia']??'')==='ruta')<x-select label="Ruta" wire:model="form.ruta_id" :options="$rutas" placeholder="Seleccionar" />@endif
 @if(($form['audiencia']??'')==='seleccionados')<x-choices label="Productores" wire:model="form.productores" :options="$productores" />@endif
 @if(($form['audiencia']??'')==='roles')<x-choices label="Roles internos" wire:model="form.roles" :options="$roles" />@endif
 <p>La lista de productores se conserva al guardar. Para cambiar la audiencia, anula el borrador y crea otro.</p><x-input label="Fecha y hora de publicación" type="datetime-local" wire:model="form.publicar_at" /><x-input label="Vencimiento opcional" type="datetime-local" wire:model="form.vence_at" />@if($editing)<x-textarea label="Motivo de corrección" wire:model="form.motivo" />@endif<x-slot:actions><x-button label="Cancelar" @click="$wire.modal=false" /><x-button label="Guardar borrador" type="submit" spinner="save" class="btn-primary" /></x-slot:actions></x-form></x-modal>
</div>
