<?php
use App\Application\Penalizaciones\GestionarPenalizaciones;
use App\Application\Penalizaciones\ConsultarPenalizaciones;
use App\Application\Operacion\ReglasOperativas;
use Illuminate\Support\Facades\Gate;
use Illuminate\Validation\ValidationException;
use Livewire\Component;
use Livewire\WithPagination;
use Livewire\Attributes\Locked;
use Mary\Traits\Toast;
new class extends Component {
 use WithPagination,Toast;
 public string $state=''; public string $producer=''; public string $reason='';
 public array $ruleForm=['activo'=>false,'tarifa_primera'=>'','tarifa_grave'=>'','alcance_tarifa'=>'','unidad_falta'=>'','ventana_dias'=>null,'motivo'=>''];
 public array $decision=['decision'=>'','decision_perdida'=>'','decision_expulsion'=>'','motivo'=>''];
 public array $assistanceForm=['estado'=>'programada','responsable_id'=>'','fecha_at'=>'','observaciones'=>'','motivo'=>''];
 #[Locked] public ?string $selected=null; #[Locked] public ?string $assistanceUuid=null;
 public function boot(): void { Gate::authorize('administrar-penalizaciones'); }
 public function mount(): void { $r=app(ReglasOperativas::class)->current('penalizaciones'); $this->ruleForm=array_intersect_key($r['valores'],$this->ruleForm)+$this->ruleForm; }
 public function updatedState(): void { Gate::authorize('administrar-penalizaciones'); $this->resetPage(); }
 public function show(string $uuid): void { Gate::authorize('administrar-penalizaciones'); app(ConsultarPenalizaciones::class)->find(auth()->id(),$uuid); $this->selected=$uuid; $this->decision=['decision'=>'','decision_perdida'=>'','decision_expulsion'=>'','motivo'=>'']; $this->resetValidation(); }
 public function showAssistance(string $uuid): void { Gate::authorize('administrar-penalizaciones'); $r=app(ConsultarPenalizaciones::class)->assistance(auth()->id(),$uuid); $this->assistanceUuid=$uuid; $this->assistanceForm=['estado'=>$r->estado==='pendiente'?'programada':$r->estado,'responsable_id'=>$r->responsable_id??'','fecha_at'=>$r->fecha_at?->format('Y-m-d\TH:i')??'','observaciones'=>$r->observaciones??'','motivo'=>'']; $this->resetValidation(); }
 public function saveRules(): void { Gate::authorize('administrar-penalizaciones'); $this->perform(function(): void { $data=$this->ruleForm; if($data['ventana_dias']==='') { $data['ventana_dias']=null; } app(GestionarPenalizaciones::class)->configure(auth()->id(),$data); $this->success('Reglas y tarifas aprobadas guardadas.'); }); }
 public function recalculate(): void { Gate::authorize('administrar-penalizaciones'); $this->perform(function(): void { $this->validate(['producer'=>'required|integer'],['required'=>'Selecciona un productor.','integer'=>'Productor inválido.']); app(GestionarPenalizaciones::class)->recalculate(auth()->id(),(int)$this->producer,$this->reason); $this->success('Recálculo controlado completado. Revisa las propuestas.'); }); }
 public function decide(): void { Gate::authorize('administrar-penalizaciones'); $this->perform(function(): void { app(GestionarPenalizaciones::class)->decide(auth()->id(),$this->selected,$this->decision); $this->success('Decisión auditada. No se ha expulsado automáticamente al productor.'); }); }
 public function annul(): void { Gate::authorize('administrar-penalizaciones'); $this->perform(function(): void { app(GestionarPenalizaciones::class)->annul(auth()->id(),$this->selected,$this->decision['motivo']); $this->success('Sanción anulada con auditoría.'); }); }
 public function saveAssistance(): void { Gate::authorize('administrar-penalizaciones'); $this->perform(function(): void { app(GestionarPenalizaciones::class)->assistance(auth()->id(),$this->assistanceUuid,$this->assistanceForm); $this->success('Asistencia actualizada.'); }); }
 private function perform(Closure $op): void { $this->resetValidation(); try { $op(); } catch(ValidationException $e) { foreach($e->errors() as $key=>$messages) { $this->addError($key,$messages[0]); } } catch(\Illuminate\Auth\Access\AuthorizationException $e) { throw $e; } catch(Throwable $e) { report($e); $this->addError('operacion','No se pudo completar la operación. Puedes reintentar.'); } }
 public function with(): array { $q=app(ConsultarPenalizaciones::class); return $q->options(auth()->id())+['records'=>$q->listing(auth()->id(),$this->state),'assistances'=>$q->assistances(auth()->id()),'detail'=>$this->selected?$q->find(auth()->id(),$this->selected):null,'audit'=>$this->selected?$q->audit(auth()->id(),$this->selected):[],'assistanceAudit'=>$this->assistanceUuid?$q->audit(auth()->id(),$this->assistanceUuid):[],'rule'=>app(ReglasOperativas::class)->current('penalizaciones')]; }
}; ?>
<div class="space-y-6"><x-header title="Penalizaciones y asistencia" subtitle="Revisión administrativa y trazabilidad de calidad" separator />
 @if($errors->any())<div class="alert alert-error" role="alert"><ul>@foreach($errors->all() as $message)<li>{{ $message }}</li>@endforeach</ul></div>@endif
 <x-card title="Evaluación controlada por productor" shadow><p>Recalcular conserva la auditoría y puede requerir una nueva decisión si cambia el análisis, la reincidencia o la regla. No ejecuta pagos ni expulsiones.</p><x-form wire:submit="recalculate"><x-select label="Productor" wire:model="producer" :options="$productores" placeholder="Seleccionar" /><x-textarea label="Motivo de evaluación o recálculo" wire:model="reason" /><x-slot:actions><x-button label="Evaluar historial" type="submit" spinner="recalculate" class="btn-primary" /></x-slot:actions></x-form></x-card>
 <x-card title="Sanciones y propuestas" shadow><x-select label="Estado" wire:model.live="state" :options="[['id'=>'pendiente_configuracion','name'=>'Falta configurar'],['id'=>'pendiente','name'=>'Pendiente'],['id'=>'aprobada','name'=>'Aprobada'],['id'=>'rechazada','name'=>'Rechazada'],['id'=>'anulada','name'=>'Anulada']]" placeholder="Todos" /><div class="overflow-x-auto"><table class="table"><thead><tr><th>Productor</th><th>Tipo / falta</th><th>Agua añadida</th><th>Tarifa</th><th>Estado</th><th></th></tr></thead><tbody>@forelse($records as $r)<tr wire:key="sancion-{{ $r->id }}"><td>{{ $r->productor->codigo }} — {{ $r->productor->nombres }}</td><td>{{ $r->tipo }} · {{ $r->numero_falta }}</td><td>{{ $r->agua_anadida }} %</td><td>{{ $r->tarifa_penalizada===null?'Sin tarifa':'S/ '.$r->tarifa_penalizada.'/L' }}</td><td>{{ str_replace('_',' ',$r->estado) }} @if($r->requiere_revision)<span class="badge badge-warning">Requiere recálculo</span>@endif</td><td><x-button label="Consultar" wire:click="show('{{ $r->uuid }}')" class="btn-sm" /></td></tr>@empty<tr><td colspan="6">No hay sanciones para este filtro. Los análisis con agua añadida generan propuestas; también puedes evaluar el historial.</td></tr>@endforelse</tbody></table></div>{{ $records->links() }}</x-card>
 @if($detail)<x-card :title="'Sanción '.$detail->uuid" shadow><p>Fuente: {{ $detail->fuente_snapshot['uuid_publico'] ?? '' }} · {{ $detail->fuente_snapshot['muestra_at'] ?? '' }}. Regla versión {{ $detail->regla_aplicada['version'] ?? 0 }}.</p><p>Alcance de tarifa: {{ $detail->regla_aplicada['valores']['alcance_tarifa'] ?? 'Sin definir' }}. Estado: {{ $detail->estado }}.</p><p>Pérdida de liquidación: {{ $detail->decision_perdida }}. Expulsión propuesta: {{ $detail->decision_expulsion }}.</p><x-form wire:submit="decide"><x-select label="Decisión de sanción" wire:model="decision.decision" :options="[['id'=>'aprobada','name'=>'Aprobar'],['id'=>'rechazada','name'=>'Rechazar']]" placeholder="Seleccionar" />@if($detail->propuesta_perdida)<x-select label="Decisión expresa sobre pérdida de liquidación" wire:model="decision.decision_perdida" :options="[['id'=>'aprobada','name'=>'Aprobar propuesta'],['id'=>'rechazada','name'=>'Rechazar propuesta']]" placeholder="Seleccionar" />@endif @if($detail->propuesta_expulsion)<x-select label="Decisión expresa sobre propuesta de expulsión" wire:model="decision.decision_expulsion" :options="[['id'=>'aprobada','name'=>'Aprobar propuesta'],['id'=>'rechazada','name'=>'Rechazar propuesta']]" placeholder="Seleccionar" /><p>Aprobar esta propuesta no desactiva al productor ni borra su información.</p>@endif<x-textarea label="Motivo obligatorio" wire:model="decision.motivo" /><x-slot:actions><x-button label="Anular sanción" wire:click="annul" spinner="annul" class="btn-error" /><x-button label="Registrar decisión" type="submit" spinner="decide" /></x-slot:actions></x-form><h3 class="font-semibold mt-3">Historial</h3>@foreach($audit as $item)<details wire:key="audit-{{ $item['id'] }}"><summary>{{ $item['accion'] }} · {{ $item['usuario']['name'] }} · {{ $item['motivo'] }}</summary><pre class="overflow-x-auto text-xs">{{ json_encode(['anterior'=>$item['anteriores'],'nuevo'=>$item['nuevos']],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre></details>@endforeach</x-card>@endif
 <x-card title="Asistencias técnicas por acidez" shadow><p>La acidez fuera del criterio vigente genera asistencia; no genera multa automática.</p><div class="overflow-x-auto"><table class="table"><thead><tr><th>Productor</th><th>Estado</th><th>Fecha</th><th>Fuente</th><th></th></tr></thead><tbody>@forelse($assistances as $r)<tr wire:key="asistencia-{{ $r->id }}"><td>{{ $r->productor->codigo }}</td><td>{{ $r->estado }}</td><td>{{ $r->fecha_at?->format('d/m/Y H:i') }}</td><td>{{ $r->requiere_revision?'Requiere revisión':($r->fuente_vigente?'Vigente':'Sin vigencia') }}</td><td><x-button label="Gestionar" wire:click="showAssistance('{{ $r->uuid }}')" class="btn-sm" /></td></tr>@empty<tr><td colspan="5">No hay asistencias detectadas.</td></tr>@endforelse</tbody></table></div>{{ $assistances->links() }}
 @if($assistanceUuid)<x-form wire:submit="saveAssistance"><x-select label="Estado" wire:model="assistanceForm.estado" :options="[['id'=>'programada','name'=>'Programada'],['id'=>'realizada','name'=>'Realizada'],['id'=>'cancelada','name'=>'Cancelada']]" /><x-select label="Responsable" wire:model="assistanceForm.responsable_id" :options="$usuarios" placeholder="Seleccionar" /><x-input label="Fecha y hora" type="datetime-local" wire:model="assistanceForm.fecha_at" /><x-textarea label="Observaciones" wire:model="assistanceForm.observaciones" /><x-textarea label="Motivo del cambio" wire:model="assistanceForm.motivo" /><x-slot:actions><x-button label="Guardar asistencia" type="submit" spinner="saveAssistance" /></x-slot:actions></x-form>@foreach($assistanceAudit as $item)<p wire:key="assistance-audit-{{ $item['id'] }}">{{ $item['accion'] }} · {{ $item['usuario']['name'] }} · {{ $item['created_at'] }} · {{ $item['motivo'] }}</p>@endforeach @endif</x-card>
 <x-card title="Reglas y tarifas penalizadas" shadow><p>Versión {{ $rule['version'] }}. No hay tarifas predefinidas; registra las aprobadas. El umbral grave es agua añadida ≥ 5 % según requisitos. La pérdida de liquidación y expulsión siempre son propuestas sujetas a revisión.</p><x-form wire:submit="saveRules"><x-checkbox label="Reglas activas" wire:model="ruleForm.activo" /><div class="grid md:grid-cols-2 gap-3"><x-input label="Tarifa de primera falta (S/ por L)" type="number" step="0.01" wire:model="ruleForm.tarifa_primera" /><x-input label="Tarifa grave (S/ por L)" type="number" step="0.01" wire:model="ruleForm.tarifa_grave" /></div><x-select label="Litros a los que se aplica la tarifa" wire:model="ruleForm.alcance_tarifa" :options="[['id'=>'entrega','name'=>'Entrega vinculada'],['id'=>'dia','name'=>'Día de muestra'],['id'=>'semana','name'=>'Semana de muestra (jueves a miércoles)']]" placeholder="Seleccionar" /><x-select label="Unidad de reincidencia" wire:model="ruleForm.unidad_falta" :options="[['id'=>'analisis','name'=>'Cada análisis con agua'],['id'=>'dia','name'=>'Cada día con agua']]" placeholder="Seleccionar" /><x-input label="Ventana de reincidencia en días (vacío = todo el historial)" type="number" step="1" wire:model="ruleForm.ventana_dias" /><x-textarea label="Motivo y referencia de aprobación" wire:model="ruleForm.motivo" /><x-slot:actions><x-button label="Guardar versión aprobada" type="submit" spinner="saveRules" /></x-slot:actions></x-form></x-card>
</div>
